import { Inter } from 'next/font/google'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <NextTopLoader 
         color="#2865E9"
         initialPosition={0.08}
         crawlSpeed={200}
         height={3}
         crawl={true}
         speed={200}
         showSpinner={false}
         zIndex={1600}
        />
        {children}
        </body>
    </html>
  )
}
